### ISSUE TITLE
Not installing properly

### ISSUE THREAD

**Issue by arunvickram** [Omikhleia/smartquotes.sile#2]
Hi!

I was trying to install `markdown.sile` to play around with it. For some reason whenever luarocks tries to install this, it's unable to actually clone the directory and install it for some reason. The other packages work perfectly fine.

```
fatal: unable to connect to github.com:
github.com[0: 140.82.114.3]: errno=Operation timed out


Error: Failed installing dependency: https://luarocks.org/dev/smartquotes.sile-dev-1.rockspec - Failed cloning git repository.
```

**Comment by Omikhleia** [comment]
Good catch @arunvickram 

A few of my other luarocks modules for SILE also had this small mistake (but weren't dependencies of the same packages).

My bad for the mess with the PR, I was on the wrong branch. Doh. Well, it should be fine now.
